config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'

  get 'cocktails/new', to: 'cocktails#new'
  post 'cocktails', to: 'cocktails#create'

  get 'cocktails/:id/doses/new', to: 'doses#new', as: 'cocktail_doses_new'
  post 'cocktails/:id/doses', to: 'doses#create', as: 'cocktail_doses'

  get 'cocktails', to: 'cocktails#index'
  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    # @cocktail.name = params[:cocktail][:name]
    # @cocktail.image_url = params[:cocktail]
    if @cocktail.save
      @dose = Dose.new(description: params[:cocktail][:doses][:description])
      @dose.cocktail = @cocktail
      @dose.ingredient = Ingredient.find(params[:cocktail][:ingredients])
      redirect_to cocktails_path if @dose.save
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image_url, :photo, :instructions)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="cards">
  <% @cocktails.each do |cocktail| %>
  <%= link_to cocktail_path(cocktail) do  %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
      <%= cocktail.name %>
    </div>
    <% end  %>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<h3>Describe your new experience</h3>
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>

  <%= f.input :ingredients, collection: @ingredients, include_blank: false, include_hidden: false %>
  <%= f.association :doses do |d|%>
    <%= d.input :description, label: "Dose" %>
  <% end %>
  <%= f.input :instructions %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, label: "Create experience" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
  <%= @cocktail.name %>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="card show-page">
      <div class="card-body">
        <h5 class="card-title">Ingredients</h5>
          <% @cocktail.doses.each do |d| %>
            <p class="card-text"><li><%= d.ingredient.name %> -- <%= d.description %></li></p>
          <% end  %>
        <%= link_to 'New ingredient', cocktail_doses_new_path(@cocktail), class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card show-page">
      <div class="card-body">
        <h5 class="card-title">Instructions</h5>
        <p class="card-text"><%= @cocktail.instructions %> </p>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h1>Add an ingredient to <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail,@dose] do |f| %>
  <%= f.association :ingredient, include_blank: false %>
  <%= f.input :description, label: "Dose" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand"<%= link_to "Refreshing.ly", cocktails_path  %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "Add new", cocktails_new_path %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>